# Generated by Django 4.1.4 on 2022-12-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200101_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exames',
            name='exame_pdf',
            field=models.FileField(upload_to='exames'),
        ),
    ]
